/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escola;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author JMTech
 */
public class Principal extends javax.swing.JFrame {

    public int p1, p2, p3;
    Aluno[] aluno = new Aluno[60];
    Professor[] professor = new Professor[60];
    Funcionario[] funcionario = new Funcionario[60];

    public void cdaluno() {
        p1 = p1 + 1;
    }

    public void cdprofessor() {
        p2 = p2 + 1;
    }

    public void cdfuncionario() {
        p3 = p3 + 1;
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PProfessor = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sexoMProfessor = new javax.swing.JCheckBox();
        sexoFProfessor = new javax.swing.JCheckBox();
        nomeProfessor = new javax.swing.JTextField();
        idadeProfessor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        salarioProfessor = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        materiaProfessor = new javax.swing.JTextField();
        lprofessor = new javax.swing.JLabel();
        PAluno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        idadeAluno = new javax.swing.JTextField();
        cursoAluno = new javax.swing.JTextField();
        sexoMAluno = new javax.swing.JCheckBox();
        sexoFAluno = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        laluno = new javax.swing.JLabel();
        PConsulta = new javax.swing.JPanel();
        c9 = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        c11 = new javax.swing.JLabel();
        c13 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        nomeconsulta = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        c12 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        PFcadastro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nomez = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        matr = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        PFuncionario = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sexoMFuncionario = new javax.swing.JCheckBox();
        sexoFFuncionario = new javax.swing.JCheckBox();
        nomeFuncionario = new javax.swing.JTextField();
        idadeFuncionario = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        salarioFuncionario = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        cargoFuncionario = new javax.swing.JTextField();
        lfuncionario = new javax.swing.JLabel();
        palterar = new javax.swing.JPanel();
        alterarTitulo = new javax.swing.JLabel();
        aConsulta = new javax.swing.JTextField();
        botaoConsulta = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        a7 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a4 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        ae = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Cadastrar Aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Consultar Aluno");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton12.setText("Alterar Aluno");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alunos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Cadastrar Professor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton16.setText("Consultar Professor");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton13.setText("Alterar Professor");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(209, 209, 209))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Professores", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Cadastrar Funcionário");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton17.setText("Consultar Funcionário");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton14.setText("Alterar Funcionário");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funcionários", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escola Barreto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPrincipal.add(Panel1, "telaprincipal");

        jLabel11.setText("Nome:");

        jLabel13.setText("Idade:");

        jLabel15.setText("Matéria:");

        sexoMProfessor.setText("Masculino");
        sexoMProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoMProfessorActionPerformed(evt);
            }
        });

        sexoFProfessor.setText("Feminino");
        sexoFProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFProfessorActionPerformed(evt);
            }
        });

        jLabel16.setText("Sexo:");

        jLabel17.setText("Salário:");

        jButton10.setText("Cadastrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Voltar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        lprofessor.setForeground(new java.awt.Color(255, 51, 51));
        lprofessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lprofessor.setText("-");

        javax.swing.GroupLayout PProfessorLayout = new javax.swing.GroupLayout(PProfessor);
        PProfessor.setLayout(PProfessorLayout);
        PProfessorLayout.setHorizontalGroup(
            PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProfessorLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PProfessorLayout.createSequentialGroup()
                        .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeProfessor)
                            .addComponent(idadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PProfessorLayout.createSequentialGroup()
                        .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PProfessorLayout.createSequentialGroup()
                                .addComponent(sexoMProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexoFProfessor))
                            .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(materiaProfessor)
                                .addComponent(salarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PProfessorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
        PProfessorLayout.setVerticalGroup(
            PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProfessorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(idadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sexoFProfessor)
                    .addComponent(sexoMProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(materiaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(salarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lprofessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap())
        );

        PanelPrincipal.add(PProfessor, "pprofessor");

        jLabel2.setText("Nome:");

        jLabel3.setText("Idade:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Curso:");

        sexoMAluno.setText("Masculino");
        sexoMAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoMAlunoActionPerformed(evt);
            }
        });

        sexoFAluno.setText("Feminino");
        sexoFAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFAlunoActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Voltar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        laluno.setForeground(new java.awt.Color(255, 51, 51));
        laluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laluno.setText("-");

        javax.swing.GroupLayout PAlunoLayout = new javax.swing.GroupLayout(PAluno);
        PAluno.setLayout(PAlunoLayout);
        PAlunoLayout.setHorizontalGroup(
            PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlunoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
            .addGroup(PAlunoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PAlunoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PAlunoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idadeAluno))
                        .addGroup(PAlunoLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(sexoMAluno)
                        .addGap(18, 18, 18)
                        .addComponent(sexoFAluno))
                    .addComponent(laluno, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        PAlunoLayout.setVerticalGroup(
            PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlunoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sexoMAluno)
                    .addComponent(sexoFAluno))
                .addGap(18, 18, 18)
                .addGroup(PAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        PanelPrincipal.add(PAluno, "paluno");

        c9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c9.setText("Nome:");

        c10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c10.setText("Idade:");

        c11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c11.setText("Sexo:");

        c13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c13.setText("Curso:");

        c2.setText("-");

        c3.setText("-");

        c4.setText("-");

        c5.setText("-");

        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        nomeconsulta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeconsulta.setText("Matrícula");

        jButton8.setText("Voltar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        c12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c12.setText("Salário:");

        c6.setText("-");

        k1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        k1.setForeground(new java.awt.Color(255, 0, 0));
        k1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        k1.setText("-");

        javax.swing.GroupLayout PConsultaLayout = new javax.swing.GroupLayout(PConsulta);
        PConsulta.setLayout(PConsultaLayout);
        PConsultaLayout.setHorizontalGroup(
            PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(210, 210, 210))
            .addGroup(PConsultaLayout.createSequentialGroup()
                .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PConsultaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(k1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PConsultaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PConsultaLayout.createSequentialGroup()
                                .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c12)
                                    .addComponent(c10)
                                    .addComponent(c11)
                                    .addComponent(c13)
                                    .addComponent(c9))
                                .addGap(18, 18, 18)
                                .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PConsultaLayout.createSequentialGroup()
                                .addComponent(nomeconsulta)
                                .addGap(18, 18, 18)
                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButton7)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        PConsultaLayout.setVerticalGroup(
            PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PConsultaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(nomeconsulta)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PConsultaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(c3))
                    .addGroup(PConsultaLayout.createSequentialGroup()
                        .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c9)
                            .addComponent(c2))
                        .addGap(18, 18, 18)
                        .addComponent(c10)
                        .addGap(18, 18, 18)
                        .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c11)
                            .addComponent(c4))
                        .addGap(18, 18, 18)
                        .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c13)
                            .addComponent(c5))
                        .addGap(18, 18, 18)
                        .addGroup(PConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c12)
                            .addComponent(c6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(k1)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(21, 21, 21))
        );

        PanelPrincipal.add(PConsulta, "pconsulta");

        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setText("Cadastro Finalizado!");

        nomez.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomez.setText("-");

        desc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desc.setText("Seu numero de matricula é:");

        matr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        matr.setForeground(new java.awt.Color(0, 102, 0));
        matr.setText("-");

        jButton9.setText("Voltar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PFcadastroLayout = new javax.swing.GroupLayout(PFcadastro);
        PFcadastro.setLayout(PFcadastroLayout);
        PFcadastroLayout.setHorizontalGroup(
            PFcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFcadastroLayout.createSequentialGroup()
                .addGroup(PFcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PFcadastroLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel10))
                    .addGroup(PFcadastroLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(nomez, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PFcadastroLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(desc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PFcadastroLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton9)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        PFcadastroLayout.setVerticalGroup(
            PFcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PFcadastroLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomez)
                .addGap(18, 18, 18)
                .addGroup(PFcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc)
                    .addComponent(matr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(55, 55, 55))
        );

        PanelPrincipal.add(PFcadastro, "pfcadastro");

        jButton18.setText("Voltar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel23.setText("Nome:");

        jLabel24.setText("Idade:");

        jLabel25.setText("Cargo:");

        sexoMFuncionario.setText("Masculino");
        sexoMFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoMFuncionarioActionPerformed(evt);
            }
        });

        sexoFFuncionario.setText("Feminino");
        sexoFFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFFuncionarioActionPerformed(evt);
            }
        });

        jLabel26.setText("Sexo:");

        jLabel27.setText("Salário:");

        jButton20.setText("Cadastrar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        lfuncionario.setForeground(new java.awt.Color(255, 51, 51));
        lfuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lfuncionario.setText("-");

        javax.swing.GroupLayout PFuncionarioLayout = new javax.swing.GroupLayout(PFuncionario);
        PFuncionario.setLayout(PFuncionarioLayout);
        PFuncionarioLayout.setHorizontalGroup(
            PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFuncionarioLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PFuncionarioLayout.createSequentialGroup()
                        .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(26, 26, 26)
                        .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeFuncionario)
                            .addComponent(idadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PFuncionarioLayout.createSequentialGroup()
                        .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addGap(22, 22, 22)
                        .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PFuncionarioLayout.createSequentialGroup()
                                .addComponent(sexoMFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sexoFFuncionario))
                            .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(salarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20))
                .addGap(181, 181, 181))
        );
        PFuncionarioLayout.setVerticalGroup(
            PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFuncionarioLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(idadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(sexoMFuncionario)
                    .addComponent(sexoFFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargoFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(salarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lfuncionario)
                .addGap(37, 37, 37)
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18)
                .addContainerGap())
        );

        PanelPrincipal.add(PFuncionario, "pfuncionario");
        PFuncionario.getAccessibleContext().setAccessibleName("");

        alterarTitulo.setText("-");

        botaoConsulta.setText("Consultar");
        botaoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaActionPerformed(evt);
            }
        });

        jButton15.setText("Voltar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        a7.setText("Nome:");

        a8.setText("Idade:");

        a11.setText("Salário:");

        a9.setText("Sexo:");

        a10.setText("Materia:");

        a4.setText("Feminino");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        a3.setText("Masculino");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        jButton19.setText("Alterar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        ae.setForeground(new java.awt.Color(0, 153, 51));
        ae.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ae.setText("Cadastro não encontrado!");

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout palterarLayout = new javax.swing.GroupLayout(palterar);
        palterar.setLayout(palterarLayout);
        palterarLayout.setHorizontalGroup(
            palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palterarLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palterarLayout.createSequentialGroup()
                        .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(palterarLayout.createSequentialGroup()
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, palterarLayout.createSequentialGroup()
                                        .addComponent(a11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, palterarLayout.createSequentialGroup()
                                        .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(palterarLayout.createSequentialGroup()
                                .addComponent(a9)
                                .addGap(18, 18, 18)
                                .addComponent(a3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palterarLayout.createSequentialGroup()
                                .addComponent(aConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(alterarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(palterarLayout.createSequentialGroup()
                                .addComponent(a8)
                                .addGap(18, 18, 18)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palterarLayout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addContainerGap())
                    .addGroup(palterarLayout.createSequentialGroup()
                        .addComponent(a7)
                        .addGap(18, 18, 18)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))))
        );
        palterarLayout.setVerticalGroup(
            palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(palterarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(alterarTitulo)
                .addGap(3, 3, 3)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsulta))
                .addGap(18, 18, 18)
                .addComponent(ae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a7)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a8)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a9)
                    .addComponent(a3)
                    .addComponent(a4))
                .addGap(6, 6, 6)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a10)
                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a11)
                    .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(palterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addGap(6, 6, 6))
        );

        PanelPrincipal.add(palterar, "palterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "paluno");
        nomeAluno.setText("");
        idadeAluno.setText("");
        sexoMAluno.setSelected(false);
        sexoFAluno.setSelected(false);
        cursoAluno.setText("");
        laluno.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            cdaluno();
            aluno[p1] = new Aluno();
            aluno[p1].setNome(nomeAluno.getText());
            aluno[p1].setIdade(Integer.parseInt(idadeAluno.getText()));
            if ((sexoMAluno.isSelected()) && (!sexoFAluno.isSelected())) {
                aluno[p1].setSexo("Masculino");
            } else if ((!sexoMAluno.isSelected()) && (sexoFAluno.isSelected())) {
                aluno[p1].setSexo("Feminino");
            }
            aluno[p1].setCurso(cursoAluno.getText());

            if ((aluno[p1].getNome().equals("")) || (aluno[p1].getIdade() == 0)
                    || (aluno[p1].getSexo().equals("")) || (aluno[p1].getCurso().equals(""))) {
                Exception ex = new Exception();
                throw ex;
            }
        } catch (Exception i) {
            p1 = p1 - 1;
            laluno.setText("Preencher corretamente os campos!");
        }
        if (aluno[p1].isValido() == false) {
            aluno[p1].setValido(true);
            nomez.setText(aluno[p1].getNome());
            desc.setText("Seu número de mátricula é: ");
            matr.setText(Integer.toString(p1));
            CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
            c1.show(PanelPrincipal, "pfcadastro");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "pconsulta");
        nomeconsulta.setText("Matrícula:");
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        k1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "pprofessor");
        nomeProfessor.setText("");
        idadeProfessor.setText("");
        sexoMProfessor.setSelected(false);
        sexoFProfessor.setSelected(false);
        materiaProfessor.setText("");
        salarioProfessor.setText("");
        lprofessor.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "palterar");
        alterarTitulo.setText("Digite a matrícula do aluno para consultar:");
        a1.setText("");
        aConsulta.setText("");
        a2.setText("");
        a5.setText("");
        a3.setSelected(false);
        a4.setSelected(false);
        a6.setVisible(false);
        a10.setText("Curso:");
        a11.setText("");
        ae.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "palterar");
        alterarTitulo.setText("Digite o código do professor para consultar:");
        a1.setText("");
        aConsulta.setText("");
        a2.setText("");
        a5.setText("");
        a3.setSelected(false);
        a4.setSelected(false);
        a6.setVisible(true);
        a10.setText("Matéria:");
        a11.setText("Salário:");
        ae.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "pconsulta");
        nomeconsulta.setText("Código:");
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        k1.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String n = nomeconsulta.getText();
        try {
            if (n.equals("Matrícula:")) {
                int a = Integer.parseInt(c1.getText());
                c2.setText(aluno[a].getNome());
                c3.setText(Integer.toString(aluno[a].getIdade()));
                c4.setText(aluno[a].getSexo());
                c5.setText(aluno[a].getCurso());
                c9.setText("Nome:");
                c10.setText("Idade:");
                c11.setText("Sexo:");
                c13.setText("Curso:");
                k1.setText("");
            } else if (n.equals("Código:")) {
                int b = Integer.parseInt(c1.getText());
                c2.setText(professor[b].getNome());
                c3.setText(Integer.toString(professor[b].getIdade()));
                c4.setText(professor[b].getSexo());
                c5.setText(professor[b].getMateria());
                c9.setText("Nome:");
                c10.setText("Idade:");
                c11.setText("Sexo:");
                c13.setText("Matéria:");
                c12.setText("Salário:");
                c6.setText("R$ " + Double.toString(professor[b].getSalario()));
                k1.setText("");
            } else if (n.equals("Cracha:")) {
                int c = Integer.parseInt(c1.getText());
                c2.setText(funcionario[c].getNome());
                c3.setText(Integer.toString(funcionario[c].getIdade()));
                c4.setText(funcionario[c].getSexo());
                c5.setText(funcionario[c].getCargo());
                c9.setText("Nome:");
                c10.setText("Idade:");
                c11.setText("Sexo:");
                c13.setText("Cargo:");
                c12.setText("Salário:");
                c6.setText("R$ " + Double.toString(funcionario[c].getSalario()));
                k1.setText("");
            }
        } catch (Exception x) {
            c1.setText("");
            c2.setText("");
            c3.setText("");
            c4.setText("");
            c5.setText("");
            c6.setText("");
            c9.setText("");
            c10.setText("");
            c11.setText("");
            c12.setText("");
            c13.setText("");
            k1.setText("Cadastro não encontrado!");
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "pfuncionario");
        nomeFuncionario.setText("");
        idadeFuncionario.setText("");
        sexoMFuncionario.setSelected(false);
        sexoFFuncionario.setSelected(false);
        cargoFuncionario.setText("");
        salarioFuncionario.setText("");
        lfuncionario.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            cdprofessor();
            professor[p2] = new Professor();
            professor[p2].setNome(nomeProfessor.getText());
            professor[p2].setIdade(Integer.parseInt(idadeProfessor.getText()));
            if ((sexoMProfessor.isSelected()) && (!sexoFProfessor.isSelected())) {
                professor[p2].setSexo("Masculino");
            } else if ((!sexoMProfessor.isSelected()) && (sexoFProfessor.isSelected())) {
                professor[p2].setSexo("Feminino");
            }
            professor[p2].setMateria(materiaProfessor.getText());
            professor[p2].setSalario(Double.parseDouble(salarioProfessor.getText()));

            if ((professor[p2].getNome().equals("")) || (professor[p2].getIdade() == 0)
                    || (professor[p2].getSexo().equals("")) || (professor[p2].getMateria().equals(""))
                    || (professor[p2].getSalario() == 0)) {
                Exception ex = new Exception();
                throw ex;
            }
        } catch (Exception e) {
            p2 = p2 - 1;
            lprofessor.setText("Preencher corretamente os campos!");
        }
        if (professor[p2].getValido() == false) {
            professor[p2].setValido(true);
            nomez.setText(professor[p2].getNome());
            desc.setText("Seu código de Professor é: ");
            matr.setText(Integer.toString(p2));
            CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
            c1.show(PanelPrincipal, "pfcadastro");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "pconsulta");
        nomeconsulta.setText("Cracha:");
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        k1.setText("");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            cdfuncionario();
            funcionario[p3] = new Funcionario();
            funcionario[p3].setNome(nomeFuncionario.getText());
            funcionario[p3].setIdade(Integer.parseInt(idadeFuncionario.getText()));
            if ((sexoMFuncionario.isSelected()) && (!sexoFFuncionario.isSelected())) {
                funcionario[p3].setSexo("Masculino");
            } else if ((!sexoMFuncionario.isSelected()) && (sexoFFuncionario.isSelected())) {
                funcionario[p3].setSexo("Feminino");
            }
            funcionario[p3].setCargo(cargoFuncionario.getText());
            funcionario[p3].setSalario(Double.parseDouble(salarioFuncionario.getText()));

            if ((funcionario[p3].getNome().equals("")) || (funcionario[p3].getIdade() == 0)
                    || (funcionario[p3].getSexo().equals("")) || (funcionario[p3].getCargo().equals(""))
                    || (funcionario[p3].getSalario() == 0)) {
                Exception ex = new Exception();
                throw ex;
            }
        } catch (Exception j) {
            p3 = p3 - 1;
            lfuncionario.setText("Preencher corretamente os campos!");
        }
        if (funcionario[p3].isValido() == false) {
            funcionario[p3].setValido(true);
            nomez.setText(funcionario[p3].getNome());
            desc.setText("Seu código de cracha de Funcionario é: ");
            matr.setText(Integer.toString(p3));
            CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
            c1.show(PanelPrincipal, "pfcadastro");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void sexoMProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoMProfessorActionPerformed
        sexoFProfessor.setSelected(false);
    }//GEN-LAST:event_sexoMProfessorActionPerformed

    private void sexoFProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFProfessorActionPerformed
        sexoMProfessor.setSelected(false);
    }//GEN-LAST:event_sexoFProfessorActionPerformed

    private void sexoMAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoMAlunoActionPerformed
        sexoFAluno.setSelected(false);
    }//GEN-LAST:event_sexoMAlunoActionPerformed

    private void sexoFAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFAlunoActionPerformed
        sexoMAluno.setSelected(false);
    }//GEN-LAST:event_sexoFAlunoActionPerformed

    private void sexoMFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoMFuncionarioActionPerformed
        sexoFFuncionario.setSelected(false);
    }//GEN-LAST:event_sexoMFuncionarioActionPerformed

    private void sexoFFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFFuncionarioActionPerformed
        sexoMFuncionario.setSelected(false);
    }//GEN-LAST:event_sexoFFuncionarioActionPerformed

    private void botaoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaActionPerformed
        String n = alterarTitulo.getText();
        try {
            if (n.equals("Digite a matrícula do aluno para consultar:")) {
                ae.setVisible(false);
                int a = Integer.parseInt(aConsulta.getText());
                a1.setText(aluno[a].getNome());
                a2.setText(Integer.toString(aluno[a].getIdade()));
                if (aluno[a].getSexo().equals("Masculino")) {
                    a3.setSelected(true);
                    a4.setSelected(false);
                } else if (aluno[a].getSexo().equals("Feminino")) {
                    a4.setSelected(true);
                    a3.setSelected(false);
                }
                a5.setText(aluno[a].getCurso());
            } else if (n.equals("Digite o código do professor para consultar:")) {
                ae.setVisible(false);
                int b = Integer.parseInt(aConsulta.getText());
                a1.setText(professor[b].getNome());
                a2.setText(Integer.toString(professor[b].getIdade()));
                if (professor[b].getSexo().equals("Masculino")) {
                    a3.setSelected(true);
                    a4.setSelected(false);
                } else if (professor[b].getSexo().equals("Feminino")) {
                    a4.setSelected(true);
                    a3.setSelected(false);
                }
                a5.setText(professor[b].getMateria());
                a6.setText(Double.toString(professor[b].getSalario()));
            } else if (n.equals("Digite o número do cracha do funcionário para consultar:")) {
                ae.setVisible(false);
                int c = Integer.parseInt(aConsulta.getText());
                a1.setText(funcionario[c].getNome());
                a2.setText(Integer.toString(funcionario[c].getIdade()));
                if (funcionario[c].getSexo().equals("Masculino")) {
                    a3.setSelected(true);
                    a4.setSelected(false);
                } else if (funcionario[c].getSexo().equals("Feminino")) {
                    a4.setSelected(true);
                    a3.setSelected(false);
                }
                a5.setText(funcionario[c].getCargo());
                a6.setText(Double.toString(funcionario[c].getSalario()));
            }
        } catch (Exception x) {
            ae.setVisible(true);
            ae.setForeground(Color.red);
            ae.setText("Cadastro não encontrado!");
            a1.setText("");
            aConsulta.setText("");
            a1.setText("");
            a2.setText("");
            a3.setSelected(false);
            a4.setSelected(false);
            a5.setText("");
            a6.setText("");
        }

    }//GEN-LAST:event_botaoConsultaActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        CardLayout c1 = (CardLayout) PanelPrincipal.getLayout();
        c1.show(PanelPrincipal, "telaprincipal");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        a4.setSelected(false);
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        a3.setSelected(false);
    }//GEN-LAST:event_a4ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            if (alterarTitulo.getText().equals("Digite a matrícula do aluno para consultar:")) {
                int r1 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {

                    aluno[r1].setNome(a1.getText());
                    aluno[r1].setIdade(Integer.parseInt(a2.getText()));
                    if ((a3.isSelected()) && (!a4.isSelected())) {
                        aluno[r1].setSexo("Masculino");
                    } else if ((!a3.isSelected()) && (a4.isSelected())) {
                        aluno[r1].setSexo("Feminino");
                    }
                    aluno[r1].setCurso(a5.getText());
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(false);
                    a10.setText("Curso:");
                    a11.setText("");
                    ae.setText("Alteração realizada!");
                    ae.setForeground(Color.blue);
                    ae.setVisible(true);
                }
            } else if (alterarTitulo.getText().equals("Digite o código do professor para consultar:")) {
                int r2 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))
                        || (a6.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {

                    professor[r2].setNome(a1.getText());
                    professor[r2].setIdade(Integer.parseInt(a2.getText()));
                    if ((a3.isSelected()) && (!a4.isSelected())) {
                        professor[r2].setSexo("Masculino");
                    } else if ((!a3.isSelected()) && (a4.isSelected())) {
                        professor[r2].setSexo("Feminino");
                    }
                    professor[r2].setMateria(a5.getText());
                    professor[r2].setSalario(Double.parseDouble(a6.getText()));
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(true);
                    a6.setText("");
                    a10.setText("Curso:");
                    a11.setText("Salário:");
                    ae.setText("Alteração realizada!");
                    ae.setForeground(Color.blue);
                    ae.setVisible(true);
                }
            } else if (alterarTitulo.getText().equals("Digite o número do cracha do funcionário para consultar:")) {
                int r3 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))
                        || (a6.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {

                    funcionario[r3].setNome(a1.getText());
                    funcionario[r3].setIdade(Integer.parseInt(a2.getText()));
                    if ((a3.isSelected()) && (!a4.isSelected())) {
                        funcionario[r3].setSexo("Masculino");
                    } else if ((!a3.isSelected()) && (a4.isSelected())) {
                        funcionario[r3].setSexo("Feminino");
                    }
                    funcionario[r3].setCargo(a5.getText());
                    funcionario[r3].setSalario(Double.parseDouble(a6.getText()));
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(true);
                    a6.setText("");
                    a10.setText("Cargo:");
                    a11.setText("Salário:");
                    ae.setText("Alteração realizada!");
                    ae.setForeground(Color.blue);
                    ae.setVisible(true);
                }
            }
        } catch (Exception ex) {
            ae.setVisible(true);
            ae.setForeground(Color.red);
            ae.setText("Preencha todos os campos!");
        }


    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        CardLayout d1 = (CardLayout) PanelPrincipal.getLayout();
        d1.show(PanelPrincipal, "palterar");
        alterarTitulo.setText("Digite o número do cracha do funcionário para consultar:");
        a1.setText("");
        aConsulta.setText("");
        a2.setText("");
        a5.setText("");
        a3.setSelected(false);
        a4.setSelected(false);
        a6.setVisible(true);
        a10.setText("Cargo:");
        a11.setText("Salário:");
        ae.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (alterarTitulo.getText().equals("Digite a matrícula do aluno para consultar:")) {
                int r1 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {
                    aluno[r1] = null;
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(false);
                    a10.setText("Curso:");
                    a11.setText("");
                    ae.setText("Cadastro Excluído!");
                    ae.setForeground(Color.red);
                    ae.setVisible(true);
                }
            } else if (alterarTitulo.getText().equals("Digite o código do professor para consultar:")) {
                int r2 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))
                        || (a6.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {
                    professor[r2] = null;
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(true);
                    a6.setText("");
                    a10.setText("Curso:");
                    a11.setText("Salário:");
                    ae.setText("Cadastro Excluído!");
                    ae.setForeground(Color.red);
                    ae.setVisible(true);
                }
            } else if (alterarTitulo.getText().equals("Digite o número do cracha do funcionário para consultar:")) {
                int r3 = Integer.parseInt(aConsulta.getText());
                ae.setVisible(false);
                if ((a1.getText().equals("")) || (a2.getText().equals(""))
                        || ((a3.isSelected() == false) && (a4.isSelected() == false)) || (a5.getText().equals(""))
                        || (a6.getText().equals(""))) {
                    Exception ex = new Exception();
                    throw ex;
                } else {
                    funcionario[r3] = null;
                    a1.setText("");
                    a2.setText("");
                    aConsulta.setText("");
                    a5.setText("");
                    a3.setSelected(false);
                    a4.setSelected(false);
                    a6.setVisible(true);
                    a6.setText("");
                    a10.setText("Cargo:");
                    a11.setText("Salário:");
                    ae.setText("Cadastro Excluído!");
                    ae.setForeground(Color.red);
                    ae.setVisible(true);
                }
            }
        } catch (Exception ex) {
            ae.setVisible(true);
            ae.setForeground(Color.red);
            ae.setText("Preencha todos os campos!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAluno;
    private javax.swing.JPanel PConsulta;
    private javax.swing.JPanel PFcadastro;
    private javax.swing.JPanel PFuncionario;
    private javax.swing.JPanel PProfessor;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextField a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JTextField a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JTextField aConsulta;
    private javax.swing.JLabel ae;
    private javax.swing.JLabel alterarTitulo;
    private javax.swing.JButton botaoConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c11;
    private javax.swing.JLabel c12;
    private javax.swing.JLabel c13;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c9;
    private javax.swing.JTextField cargoFuncionario;
    private javax.swing.JTextField cursoAluno;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField idadeAluno;
    private javax.swing.JTextField idadeFuncionario;
    private javax.swing.JTextField idadeProfessor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel laluno;
    private javax.swing.JLabel lfuncionario;
    private javax.swing.JLabel lprofessor;
    private javax.swing.JTextField materiaProfessor;
    private javax.swing.JLabel matr;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JTextField nomeProfessor;
    private javax.swing.JLabel nomeconsulta;
    private javax.swing.JLabel nomez;
    private javax.swing.JPanel palterar;
    private javax.swing.JTextField salarioFuncionario;
    private javax.swing.JTextField salarioProfessor;
    private javax.swing.JCheckBox sexoFAluno;
    private javax.swing.JCheckBox sexoFFuncionario;
    private javax.swing.JCheckBox sexoFProfessor;
    private javax.swing.JCheckBox sexoMAluno;
    private javax.swing.JCheckBox sexoMFuncionario;
    private javax.swing.JCheckBox sexoMProfessor;
    // End of variables declaration//GEN-END:variables
}
